baseURL      = "https://yam8511.github.io/zero/"
languageCode = "zh-tw"
title        = "Learn from ZerO"
theme        = "soho"

# enableInlineShortcodes = true

# summarylength = 10
# enableEmoji = true

[params]
author = "Zuolar (阿俊)"
description = "隨手筆記、技術大小事、學習心得、生活趣事"

## Set one of:
gravatar = "yma8511@gmail.com"
# profilePicture = "007.png"
